# Generated by Django 3.0 on 2022-01-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_bodega',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
